import { z } from "zod";

const optionalPhone = z
  .string()
  .trim()
  .max(50, "Number is too long")
  .regex(/^[+\d\s()-]+$/, "Invalid number format")
  .optional()
  .or(z.literal(""));

const optionalUrl = z
  .string()
  .url("Please enter a valid URL")
  .max(2000, "URL is too long")
  .optional()
  .or(z.literal(""));

const customButtonSchema = z.object({
  label: z
    .string()
    .min(1, "Button label is required")
    .max(50, "Label is too long"),
  url: z
    .string()
    .url("Invalid URL")
    .max(2000, "URL is too long"),
});

const pageBaseSchema = z.object({
  businessName: z
    .string()
    .min(2, "Business name must be at least 2 characters")
    .max(255, "Business name is too long"),
  businessType: z
    .string()
    .min(2, "Please describe your business type")
    .max(100, "Business type is too long"),
  phoneNumber: optionalPhone,
  whatsappNumber: optionalPhone,
  instagramUrl: optionalUrl,
  youtubeUrl: optionalUrl,
  googleMapsUrl: optionalUrl,
  customButtons: z.array(customButtonSchema).optional(),
});

const hasContactMethod = (data: { phoneNumber?: string; whatsappNumber?: string; googleMapsUrl?: string }) =>
  Boolean(data.phoneNumber || data.whatsappNumber || data.googleMapsUrl);

const contactRefine = {
  message: "Add at least one contact method (Phone, WhatsApp, or Maps)",
  path: ["phoneNumber"],
};

export const pageSchema = pageBaseSchema.refine(hasContactMethod, contactRefine);

// Super admin pages: tagline and the 5 benefits are typed manually instead of
// being generated by AI.
export const superPageSchema = pageBaseSchema
  .extend({
    // Optional custom slug. Leave blank to auto-generate a code.
    slug: z
      .string()
      .trim()
      .toLowerCase()
      .min(3, "Slug must be at least 3 characters")
      .max(64, "Slug is too long")
      .regex(
        /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
        "Use lowercase letters, numbers, and hyphens only"
      )
      .optional()
      .or(z.literal("")),
    tagline: z
      .string()
      .trim()
      .min(2, "Tagline is required")
      .max(255, "Tagline is too long"),
    benefits: z
      .array(z.string().trim().min(1, "Benefit cannot be empty").max(120, "Benefit is too long"))
      .min(1, "Add at least one benefit")
      .max(10, "You can add up to 10 benefits"),
  })
  .refine(hasContactMethod, contactRefine);

export const shopSchema = z.object({
  shopName: z
    .string()
    .min(2, "Shop name must be at least 2 characters")
    .max(255, "Shop name is too long"),
  ownerName: z
    .string()
    .min(2, "Owner name must be at least 2 characters")
    .max(255, "Owner name is too long"),
  ownerPhone: z
    .string()
    .trim()
    .min(6, "Enter a valid phone number")
    .max(50, "Number is too long")
    .regex(/^[+\d\s()-]+$/, "Invalid number format"),
});

export const pinLoginSchema = z.object({
  pin: z.string().regex(/^\d{4,6}$/, "Enter your PIN"),
});

export const shopLoginSchema = z.object({
  ownerName: z
    .string()
    .trim()
    .min(2, "Enter your name")
    .max(255, "Name is too long"),
  pin: z.string().regex(/^\d{4,6}$/, "Enter your PIN"),
});

export type PageFormData = z.infer<typeof pageSchema>;
export type SuperPageFormData = z.infer<typeof superPageSchema>;
export type ShopFormData = z.infer<typeof shopSchema>;
export type CustomButton = z.infer<typeof customButtonSchema>;
